# Introduction to Pandas Lab

Complete the following set of exercises to solidify your knowledge of Pandas fundamentals.

### 1. Import Numpy and Pandas and alias them to `np` and `pd` respectively.

In [26]:
import pandas as pd
import numpy as np

### 2. Create a Pandas Series containing the elements of the list below.

In [27]:
lst = [5.7, 75.2, 74.4, 84.0, 66.5, 66.3, 55.8, 75.7, 29.1, 43.7]

In [28]:
# your code here
df = pd.Series(lst)
df

0     5.7
1    75.2
2    74.4
3    84.0
4    66.5
5    66.3
6    55.8
7    75.7
8    29.1
9    43.7
dtype: float64

### 3. Use indexing to return the third value in the Series above.

*Hint: Remember that indexing begins at 0.*

In [29]:
# your code here
print(df[2])

74.4

### 4. Create a Pandas DataFrame from the list of lists below. Each sublist should be represented as a row.

In [30]:
b = [[53.1, 95.0, 67.5, 35.0, 78.4],
     [61.3, 40.8, 30.8, 37.8, 87.6],
     [20.6, 73.2, 44.2, 14.6, 91.8],
     [57.4, 0.1, 96.1, 4.2, 69.5],
     [83.6, 20.5, 85.4, 22.8, 35.9],
     [49.0, 69.0, 0.1, 31.8, 89.1],
     [23.3, 40.7, 95.0, 83.8, 26.9],
     [27.6, 26.4, 53.8, 88.8, 68.5],
     [96.6, 96.4, 53.4, 72.4, 50.1],
     [73.7, 39.0, 43.2, 81.6, 34.7]]

In [31]:
# your code here
df = pd.DataFrame(b)
df

      0     1     2     3     4
0  53.1  95.0  67.5  35.0  78.4
1  61.3  40.8  30.8  37.8  87.6
2  20.6  73.2  44.2  14.6  91.8
3  57.4   0.1  96.1   4.2  69.5
4  83.6  20.5  85.4  22.8  35.9
5  49.0  69.0   0.1  31.8  89.1
6  23.3  40.7  95.0  83.8  26.9
7  27.6  26.4  53.8  88.8  68.5
8  96.6  96.4  53.4  72.4  50.1
9  73.7  39.0  43.2  81.6  34.7

### 5. Rename the data frame columns based on the names in the list below.

```py
list_names = ["Score_1", "Score_2", "Score_3", "Score_4", "Score_5"]
```

In [32]:
b = [[53.1, 95.0, 67.5, 35.0, 78.4],
     [61.3, 40.8, 30.8, 37.8, 87.6],
     [20.6, 73.2, 44.2, 14.6, 91.8],
     [57.4, 0.1, 96.1, 4.2, 69.5],
     [83.6, 20.5, 85.4, 22.8, 35.9],
     [49.0, 69.0, 0.1, 31.8, 89.1],
     [23.3, 40.7, 95.0, 83.8, 26.9],
     [27.6, 26.4, 53.8, 88.8, 68.5],
     [96.6, 96.4, 53.4, 72.4, 50.1],
     [73.7, 39.0, 43.2, 81.6, 34.7]]

In [33]:
# your code here
lst_names = ["Score_1", "Score_2", "Score_3", "Score_4", "Score_5"]
df.columns = lst_names
df

   Score_1  Score_2  Score_3  Score_4  Score_5
0     53.1     95.0     67.5     35.0     78.4
1     61.3     40.8     30.8     37.8     87.6
2     20.6     73.2     44.2     14.6     91.8
3     57.4      0.1     96.1      4.2     69.5
4     83.6     20.5     85.4     22.8     35.9
5     49.0     69.0      0.1     31.8     89.1
6     23.3     40.7     95.0     83.8     26.9
7     27.6     26.4     53.8     88.8     68.5
8     96.6     96.4     53.4     72.4     50.1
9     73.7     39.0     43.2     81.6     34.7

In [15]:
"""
b = [["Score_1", "Score_2", "Score_3", "Score_4", "Score_5"],
     [53.1, 95.0, 67.5, 35.0, 78.4],
     [61.3, 40.8, 30.8, 37.8, 87.6],
     [20.6, 73.2, 44.2, 14.6, 91.8],
     [57.4, 0.1, 96.1, 4.2, 69.5],
     [83.6, 20.5, 85.4, 22.8, 35.9],
     [49.0, 69.0, 0.1, 31.8, 89.1],
     [23.3, 40.7, 95.0, 83.8, 26.9],
     [27.6, 26.4, 53.8, 88.8, 68.5],
     [96.6, 96.4, 53.4, 72.4, 50.1],
     [73.7, 39.0, 43.2, 81.6, 34.7]]

df = pd.DataFrame(b)
df
"""
#simply adding of data will not include in the columns rather it will be counted as 1st row

          0        1        2        3        4
0   Score_1  Score_2  Score_3  Score_4  Score_5
1      53.1     95.0     67.5     35.0     78.4
2      61.3     40.8     30.8     37.8     87.6
3      20.6     73.2     44.2     14.6     91.8
4      57.4      0.1     96.1      4.2     69.5
5      83.6     20.5     85.4     22.8     35.9
6      49.0     69.0      0.1     31.8     89.1
7      23.3     40.7     95.0     83.8     26.9
8      27.6     26.4     53.8     88.8     68.5
9      96.6     96.4     53.4     72.4     50.1
10     73.7     39.0     43.2     81.6     34.7

### 6. Create a subset of this data frame that contains only the Score 1, 3, and 5 columns.

In [34]:
# your code here
subset_of_df = df[["Score_1", "Score_3", "Score_5"]]
subset_of_df

   Score_1  Score_3  Score_5
0     53.1     67.5     78.4
1     61.3     30.8     87.6
2     20.6     44.2     91.8
3     57.4     96.1     69.5
4     83.6     85.4     35.9
5     49.0      0.1     89.1
6     23.3     95.0     26.9
7     27.6     53.8     68.5
8     96.6     53.4     50.1
9     73.7     43.2     34.7

### 7. From the original data frame, calculate the average Score_3 value.

In [35]:
# your code here
Average_Score_3 = df["Score_3"].mean()
Average_Score_3

np.float64(56.95000000000001)

### 8. From the original data frame, calculate the maximum Score_4 value.

In [37]:
# your code here
Maximum_Score_4 = df["Score_4"].max()
Maximum_Score_4

88.8

### 9. From the original data frame, calculate the median Score 2 value.

In [39]:
# your code here
Median_Score_2 = df["Score_2"].median()
Median_Score_2

40.75

### 10. Create a Pandas DataFrame from the dictionary of product orders below.

In [40]:
orders = {'Description': ['LUNCH BAG APPLE DESIGN',
  'SET OF 60 VINTAGE LEAF CAKE CASES ',
  'RIBBON REEL STRIPES DESIGN ',
  'WORLD WAR 2 GLIDERS ASSTD DESIGNS',
  'PLAYING CARDS JUBILEE UNION JACK',
  'POPCORN HOLDER',
  'BOX OF VINTAGE ALPHABET BLOCKS',
  'PARTY BUNTING',
  'JAZZ HEARTS ADDRESS BOOK',
  'SET OF 4 SANTA PLACE SETTINGS'],
 'Quantity': [1, 24, 1, 2880, 2, 7, 1, 4, 10, 48],
 'UnitPrice': [1.65, 0.55, 1.65, 0.18, 1.25, 0.85, 11.95, 4.95, 0.19, 1.25],
 'Revenue': [1.65, 13.2, 1.65, 518.4, 2.5, 5.95, 11.95, 19.8, 1.9, 60.0]}

In [41]:
# your code here
df = pd.DataFrame(orders)
df

                          Description  Quantity  UnitPrice  Revenue
0              LUNCH BAG APPLE DESIGN         1       1.65     1.65
1  SET OF 60 VINTAGE LEAF CAKE CASES         24       0.55    13.20
2         RIBBON REEL STRIPES DESIGN          1       1.65     1.65
3   WORLD WAR 2 GLIDERS ASSTD DESIGNS      2880       0.18   518.40
4    PLAYING CARDS JUBILEE UNION JACK         2       1.25     2.50
5                      POPCORN HOLDER         7       0.85     5.95
6      BOX OF VINTAGE ALPHABET BLOCKS         1      11.95    11.95
7                       PARTY BUNTING         4       4.95    19.80
8            JAZZ HEARTS ADDRESS BOOK        10       0.19     1.90
9       SET OF 4 SANTA PLACE SETTINGS        48       1.25    60.00

### 11. Calculate the total quantity ordered and revenue generated from these orders.

In [45]:
# your code here
total_quantity_orders = df['Quantity'].sum()
print(total_quantity_orders)
total_revenue_generated = df['Revenue'].sum()
print(total_revenue_generated)

2978
637.0

### 12. Obtain the prices of the most expensive and least expensive items ordered and print the difference.

In [52]:
# your code here
most_expensive = df['UnitPrice'].idxmax()
Most_expensive_item = df.loc[most_expensive, 'Description']
print("Most expensive item: ", Most_expensive_item)
least_expensive = df['UnitPrice'].idxmin()
least_expensive_item = df.loc[least_expensive, 'Description']
print("Least expensive item: ", least_expensive_item)

Most expensive item:  BOX OF VINTAGE ALPHABET BLOCKS
Least expensive item:  WORLD WAR 2 GLIDERS ASSTD DESIGNS

## Let's load another dataset for more exercisesº

In [55]:
# Run this code:
admissions = pd.read_csv('../Admission_Predict.csv')

Let's evaluate the dataset by looking at the `head` function.

In [57]:
# your code here
admissions.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,316,104,3,3.0,3.5,8.00,1,0.72
2,3,322,110,3,3.5,2.5,8.67,1,0.80
3,4,314,103,2,2.0,3.0,8.21,0,0.65
4,5,330,115,5,4.5,3.0,9.34,1,0.90

### 1 - Before beginning to work with this dataset and evaluating graduate admissions data, we will verify that there is no missing data in the dataset. Do this in the cell below.

In [58]:
# your code here
admissions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385 entries, 0 to 384
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         385 non-null    int64
 1   GRE Score          385 non-null    int64
 2   TOEFL Score        385 non-null    int64
 3   University Rating  385 non-null    int64
 4   SOP                385 non-null    float64
 5   LOR                385 non-null    float64
 6   CGPA               385 non-null    float64
 7   Research           385 non-null    int64
 8   Chance of Admit    385 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 27.2 KB

###  2 -  Interestingly, there is a column that uniquely identifies the applicants. This column is the serial number column. Instead of having our own index, we should make this column our index. Do this in the cell below. Keep the column in the dataframe in addition to making it an index.

In [59]:
# your code here
admissions.index = admissions['Serial No.']
admissions.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,,
1,1,337,118,4,4.5,4.5,9.65,1,0.92
2,2,316,104,3,3.0,3.5,8.00,1,0.72
3,3,322,110,3,3.5,2.5,8.67,1,0.80
4,4,314,103,2,2.0,3.0,8.21,0,0.65
5,5,330,115,5,4.5,3.0,9.34,1,0.90

Turns out that `GRE Score` and `CGPA` also uniquely identify the data. Show this in the cell below.

### 3 - In this part of the lab, we would like to test complex conditions on the entire data set at once. Let's start by finding the number of rows where the CGPA is greater than 9 and the student has performed an investigation.

In [64]:
# your code here
len(admissions[(admissions["CGPA"] > 9) & (admissions["Research"] == 1)])

101

### 4 - Now return all the rows where the CGPA is greater than 9 and the SOP score is less than 3.5. Find the mean chance of admit for these applicants.

In [67]:
# your code here
Ans_of_1st_part = admissions[(admissions["CGPA"] > 9) & (admissions["SOP"] < 3.5)]
Ans_of_1st_part

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,,
29,29,338,118,4,3.0,4.5,9.40,1,0.91
63,63,327,114,3,3.0,3.0,9.02,0,0.61
141,141,326,114,3,3.0,3.0,9.11,1,0.83
218,218,324,111,4,3.0,3.0,9.01,1,0.82
382,382,325,107,3,3.0,3.5,9.11,1,0.84

In [71]:
Mean_chance_of_admit = Ans_of_1st_part["Chance of Admit "].mean()
print(Mean_chance_of_admit)

0.8019999999999999